// Local product image fallbacks — keyed by product slug
export const LOCAL_IMAGES: Record<string, string> = {
  // ── Μοσχάρι ──────────────────────────────────────────────────
  'mosxari-kiloto':                  '/images/products/BottomRound.jpg',
  'mosxari-noua':                    '/images/products/HNG_sirloin.jpg',
  'mosxari-elia':                    '/images/products/Bavette.jpg',
  'mosxari-spala':                   '/images/products/product-beef-chuck-roast.jpg',
  'mosxari-strongilo':               '/images/products/BottomRound.jpg',
  'mosxari-trans':                   '/images/products/StewMeat.jpg',
  'mosxari-oura':                    '/images/products/Oxtail.jpg',
  'mosxari-pontiki':                 '/images/products/product-beef-flank-steak-recrop.jpg',
  'mosxari-xteni':                   '/images/products/product-beef-flap-steak-recrop.jpg',
  'mosxari-tortukita':               '/images/products/ChuckEye.jpg',
  'mosxari-spalomita':               '/images/products/product-beef-pacanha.jpg',
  'mosxari-sidirodromos':            '/images/products/KCStrip.jpg',
  'mosxari-stithos-kokkalo':         '/images/products/KoreanShortRib.webp',
  // ── Αρνί & Κατσίκι ───────────────────────────────────────────
  'arni':                            '/images/products/Vacio.jpg',
  'provato-bouti-spala':             '/images/products/Vacio.jpg',
  'provato-fileto-bouti':            '/images/products/SirloinFilet.jpg',
  'provato-paidaki':                 '/images/products/KoreanShortRib.webp',
  'gida':                            '/images/products/StewMeat.jpg',
  'zygouri':                         '/images/products/Vacio.jpg',
  // ── Χοιρινό ──────────────────────────────────────────────────
  'xoirino-brizola':                 '/images/products/product-pork-boneless-pork-chop.jpg',
  'xoirino-brizola-laimou':          '/images/products/product-pork-boneless-pork-chop.jpg',
  'xoirino-brizola-laimou-boneless': '/images/products/product-pork-boneless-pork-chop.jpg',
  'xoirino-stavlisia':               '/images/products/Pork.jpg',
  'xoirino-spala':                   '/images/products/PorkButtHalf.jpg',
  'xoirino-bouti':                   '/images/products/Pork.jpg',
  'xoirino-snitsel':                 '/images/products/product-pork-boneless-pork-chop.jpg',
  'xoirino-kotsi':                   '/images/products/Pork.jpg',
  'xoirino-panseta':                 '/images/products/product-pork-bacon.jpg',
  // ── Πουλερικά ────────────────────────────────────────────────
  'kotopoulo-olokliro':              '/images/products/Chicken_thighs_bonein.jpg',
  'kotopoulo-olokliro-xekok':        '/images/products/GrassRootsGroundChicken1.png',
  'kotopoulo-bouti':                 '/images/products/Chicken_thighs_bonein.jpg',
  'kotopoulo-stithos':               '/images/products/GrassRootsGroundChicken1.png',
  'kotopoulo-fteruges':              '/images/products/Chicken_flats_drumettes.jpg',
  'kotopoulo-fileto-bouti':          '/images/products/Chicken_thighs_bonein.jpg',
  'kotopoulo-fileto-stithos':        '/images/products/GrassRootsGroundChicken1.png',
  'kokorasp':                        '/images/products/Drumstickspdp.webp',
  // ── Παρασκευάσματα — Μοσχάρι ─────────────────────────────────
  'mosxari-bifteki':                 '/images/products/HalfLBPatty.jpg',
  'mosxari-arni-kebap':              '/images/products/PALEO_BLEND.jpg',
  'mosxari-rolo':                    '/images/products/product-beef-ground-beef.jpg',
  'mosxari-gyros':                   '/images/products/product-beef-large-skirt-steak.jpg',
  'mosxari-loukaniko':               '/images/products/Hot-Italian-Links.jpg',
  'mosxari-soutzouki':               '/images/products/Chorizo.jpg',
  // ── Παρασκευάσματα — Χοιρινό ─────────────────────────────────
  'xoirino-kontosouvlia':            '/images/products/PorkSpareRibs.jpg',
  'xoirino-panarisma-snitsel':       '/images/products/product-pork-boneless-pork-chop.jpg',
  'xoirino-brizolakia-marina':       '/images/products/product-pork-boneless-pork-chop.jpg',
  'xoirino-panseta-bbq':             '/images/products/product-pork-bacon.jpg',
  'xoirino-gyros':                   '/images/products/GroundPork.jpg',
  'xoirino-souvlaki':                '/images/products/PorkSpareRibs.jpg',
  'xoirino-kotsi-bira':              '/images/products/Pork.jpg',
  'xoirino-kotsi-patates-bbq':       '/images/products/Pork.jpg',
  'xoirino-spetsofai':               '/images/products/Chorizo.jpg',
  'xoirino-loukaniko-praso':         '/images/products/Kielbase.jpg',
  'xoirino-loukaniko-kaytero':       '/images/products/Hot-Italian-Links.jpg',
  'mixed-loukaniko':                 '/images/products/Bratwurst.jpg',
  // ── Παρασκευάσματα — Κοτόπουλο ───────────────────────────────
  'kotopoulo-bifteki':               '/images/products/HalfLBPatty.jpg',
  'kotopoulo-rolo':                  '/images/products/GrassRootsGroundChicken1.png',
  'kotopoulo-kotompoukies':          '/images/products/Drumstickspdp.webp',
  'kotopoulo-snitsel':               '/images/products/Chicken_thighs_bonein.jpg',
  'kotopoulo-gyros':                 '/images/products/Chicken_flats_drumettes.jpg',
  'kotopoulo-kontosouvlia':          '/images/products/Chicken_flats_drumettes.jpg',
  'kotopoulo-souvlaki':              '/images/products/Chicken_flats_drumettes.jpg',
  'kotopoulo-stithos-marina':        '/images/products/GrassRootsGroundChicken1.png',
  'kotopoulo-bouti-marina':          '/images/products/Chicken_thighs_bonein.jpg',
  'kotopoulo-glukoksino':            '/images/products/Chicken_thighs_bonein.jpg',
  'kotopoulo-krema-tirion':          '/images/products/GrassRootsGroundChicken1.png',
}
